# Generated by Django 4.2.2 on 2023-06-16 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='music')),
                ('visibility', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Protected', 'Protected')], default='Public', max_length=10)),
                ('emails', models.TextField(blank=True, help_text='Enter email addresses separated by commas (,)')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
