# Generated by Django 4.2.2 on 2023-06-16 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_musicfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MusicFile',
            new_name='MusicFiles',
        ),
    ]
