# Generated by Django 4.2.2 on 2023-06-16 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_musicfile_musicfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicfiles',
            name='emails',
        ),
        migrations.AddField(
            model_name='musicfiles',
            name='emails',
            field=models.ManyToManyField(blank=True, related_name='protected_music', to=settings.AUTH_USER_MODEL),
        ),
    ]
