# Generated by Django 4.2.2 on 2023-06-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_musicfiles_emails_musicfiles_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicfiles',
            name='singer',
            field=models.CharField(default='none', max_length=250),
        ),
    ]
