# Generated by Django 4.2.2 on 2023-06-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_musicfiles_singer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicfiles',
            name='visibility',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Protected', 'Protected')], max_length=10, null=True),
        ),
    ]
