# Generated by Django 4.2.2 on 2023-06-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_musicfiles_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicfiles',
            name='singer',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='musicfiles',
            name='visibility',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Protected', 'Protected')], default='Public', max_length=10),
        ),
    ]
