# Generated by Django 4.2.2 on 2023-06-16 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_musicfiles_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MusicFiles',
            new_name='MusicFile',
        ),
    ]
