# Generated by Django 4.2.2 on 2023-06-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_musicfiles_musicfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicfile',
            name='visibility',
            field=models.CharField(choices=[('Public', 'public'), ('Private', 'private'), ('Protected', 'protected')], default='Public', max_length=10),
        ),
    ]
