# Generated by Django 4.2.2 on 2023-06-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_musicfile_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicfile',
            name='visibility',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Protected', 'Protected')], default='Public', max_length=10),
        ),
    ]
